spec:
  name: pompom
  services:
    - name: web
      environment_slug: node-js
      github:
        repo: DoctorKhan/PomPom
        branch: main
        deploy_on_push: true
      build_command: npm run build
      run_command: npm start
      source_dir: / 
      http_port: ${PORT}
      instance_count: 1
      instance_size_slug: basic-xxs
      routes:
        - path: /
      health_check:
        http_path: /api/health
      envs:
        - key: GROQ_API_KEY
          scope: RUN_TIME
          type: SECRET
          value: "${GROQ_API_KEY}"

